theme = "native"
icons = "awesome"

[[block]]
block = "custom"
command = "curl api.ipify.org"

[[block]]
block = "net"
device = "enp6s0"
format = "{speed_down} {graph_down}"
interval = 5
use_bits = false

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
