# This is a basic workflow to help you get started with Actions

name: Push ideas to gist

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in paralle

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.0.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/danielmichaels/4b8bad44478c52cf0ce28731b39b6046
          gist_title: Ideation
          gist_description: A list of random idea; mostly useless
          github_file: playbook/pages/Ideation.md
