# This is a basic workflow to help you get started with Actions

name: Push ideas to gist

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: gist-sync
      uses: Popsiclestick/gist-sync-action@v1.0.0
      with:
    # Auth token with gist permissions
        auth: c47f0a7db1257a1617d8a0f0a52b78a2da44e99e
    # URL of the gist
        gist_url: https://gist.github.com/danielmichaels/4b8bad44478c52cf0ce28731b39b6046
    # Title of the gist
        gist_title: ideation
    # Description of the gist
        gist_description: A list of random idea; mostly useless
    # The Filename with the contents we want to mirror
        github_file: https://github.com/danielmichaels/databank/blob/master/playbook/pages/Ideation.md
